### ISSUE TITLE
checkout: mobile drawer doesn't scroll properly

### ISSUE THREAD

**Issue by zeekay** [luxdefi/www#84]
Please ensure we use https://ui.shadcn.com/docs/components/scroll-area for the right behavior when selecting variant to add to cart from mobile drawer view.

**Comment by artemis-prime** [comment]
Wo a screenshot I don't know what you mean

Suggestions Re impl are not as helpful as descriptions of the issue. I'm using a scrolling wheel.  Please either screenshot or further clarify

**Comment by zeekay** [comment]
Use the shadcn component on mac it does not work as expected.

**Comment by artemis-prime** [comment]
fixed in todays build, but please test
